# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bot_pb2 as bot__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BotServiceStub(object):
    """gRPC Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamBotCrawlUrl = channel.stream_stream(
                '/bot.BotService/StreamBotCrawlUrl',
                request_serializer=bot__pb2.BotCommand.SerializeToString,
                response_deserializer=bot__pb2.BotLog.FromString,
                _registered_method=True)
        self.StreamBotCrawlDetail = channel.stream_stream(
                '/bot.BotService/StreamBotCrawlDetail',
                request_serializer=bot__pb2.BotCommand.SerializeToString,
                response_deserializer=bot__pb2.BotLog.FromString,
                _registered_method=True)


class BotServiceServicer(object):
    """gRPC Service
    """

    def StreamBotCrawlUrl(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBotCrawlDetail(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamBotCrawlUrl': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamBotCrawlUrl,
                    request_deserializer=bot__pb2.BotCommand.FromString,
                    response_serializer=bot__pb2.BotLog.SerializeToString,
            ),
            'StreamBotCrawlDetail': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamBotCrawlDetail,
                    request_deserializer=bot__pb2.BotCommand.FromString,
                    response_serializer=bot__pb2.BotLog.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bot.BotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bot.BotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BotService(object):
    """gRPC Service
    """

    @staticmethod
    def StreamBotCrawlUrl(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/bot.BotService/StreamBotCrawlUrl',
            bot__pb2.BotCommand.SerializeToString,
            bot__pb2.BotLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBotCrawlDetail(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/bot.BotService/StreamBotCrawlDetail',
            bot__pb2.BotCommand.SerializeToString,
            bot__pb2.BotLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
