# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bot.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'bot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbot.proto\x12\x03\x62ot\"k\n\nBotCommand\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.bot.BotCommand.CommandType\x12\x0e\n\x06\x62ot_id\x18\x02 \x01(\t\"\"\n\x0b\x43ommandType\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\")\n\x06\x42otLog\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2}\n\nBotService\x12\x35\n\x11StreamBotCrawlUrl\x12\x0f.bot.BotCommand\x1a\x0b.bot.BotLog(\x01\x30\x01\x12\x38\n\x14StreamBotCrawlDetail\x12\x0f.bot.BotCommand\x1a\x0b.bot.BotLog(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOTCOMMAND']._serialized_start=18
  _globals['_BOTCOMMAND']._serialized_end=125
  _globals['_BOTCOMMAND_COMMANDTYPE']._serialized_start=91
  _globals['_BOTCOMMAND_COMMANDTYPE']._serialized_end=125
  _globals['_BOTLOG']._serialized_start=127
  _globals['_BOTLOG']._serialized_end=168
  _globals['_BOTSERVICE']._serialized_start=170
  _globals['_BOTSERVICE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
